name         'ngiger-jubula'
version      '0.1.0'
summary      'jubula Puppet module.'
description  'Puppet module for installing jubula (Was part of elexis-vagrant til August 2014)'
project_page 'https://github.com/ngiger/puppet-jubula'
license      'GNU General Public License v3 or Later (GPLv3+)'
author       'Niklaus Giger <niklaus.giger@member.fsf.org>'
dependency   'puppetlabs/apt', '>= 1.0.0'
